import { useEffect, useMemo, useState } from "react";
import {
  Activity, ArrowLeftRight, BookOpen, ChevronRight, Crosshair, Database, Download, History,
  Info, Library, MoreHorizontal, Play, Save, Shield, ShieldCheck, Swords, Upload,
} from "lucide-react";
import "./arena.css";
import {
  ARENA_HISTORY_KEY, ARENA_PATCH, ARENA_STORAGE_KEY, PATH_PROFILES,
  decodeArenaShare, encodeArenaShare, loadArenaHistory, loadArenaState, readPveInventorySnapshot,
  saveArenaHistory, saveArenaState,
} from "./arena-core.mjs";
import {
  ARENA_ATTUNEMENT_CATALOG, ARENA_MODE_IDS, ARENA_MODE_RULES,
  BAMBOOCUT_DUST_ARENA, BATTLEGROUPS, COMPETITIVE_PATCH, EVIDENCE_MATRIX, EVIDENCE_STATE,
  LEVEL_ADJUSTMENT, NETWORK_RESOLUTION, PATH_COMPETITIVE_PROFILES, PERCEPTION_FOREST,
  P0_CLIENT_CAPTURE_CHECKLIST, applyCombatEvent, attunementDecision, canOptimizeNumericStats,
  createArenaCombatState, matchupAnalysis, validate3v3Rules,
} from "../competitive/competitive-v2.mjs";

type Route = "overview" | "build" | "matchups" | "compare" | "simulation" | "history" | "attunement" | "skills" | "evidence" | "reference" | "transfer";
type ArenaState = ReturnType<typeof loadArenaState>;
type ArenaModeV2 = typeof ARENA_MODE_IDS[number];

const PRIMARY: Array<{ id: Route; label: string; icon: typeof Activity }> = [
  { id: "overview", label: "Overview", icon: Activity },
  { id: "build", label: "Build", icon: Shield },
  { id: "matchups", label: "Matchups", icon: Crosshair },
  { id: "compare", label: "Compare", icon: ArrowLeftRight },
  { id: "simulation", label: "Simulation", icon: Play },
  { id: "history", label: "History", icon: History },
];
const SECONDARY: Array<{ id: Route; label: string }> = [
  { id: "attunement", label: "Attunement" }, { id: "skills", label: "Mechanics" },
  { id: "evidence", label: "Evidence" }, { id: "reference", label: "Path Catalog" }, { id: "transfer", label: "Import / Export" },
];
const PATHS = Object.keys(PATH_COMPETITIVE_PROFILES);

function routeFromHash(): Route {
  const value = location.hash.replace(/^#arena\/?/, "").split("/")[0];
  return [...PRIMARY, ...SECONDARY].some((item) => item.id === value) ? value as Route : "overview";
}
function sharedTokenFromHash() { const match = location.hash.match(/^#arena\/shared\/(.+)$/); return match?.[1] || ""; }
function go(route: Route) { location.hash = `#arena/${route}`; }
function evidenceLabel(value: string) { return value.replaceAll("_", " "); }
function legacyMode(mode: ArenaModeV2) { return mode === "3V3_ARENA" ? "3v3" : mode === "GROUP_STRATEGY" || mode === "5V5_ARENA" ? "5v5" : "1v1"; }
function initialMode(state: any, profile: any): ArenaModeV2 { // ARENA_CANONICAL_V2_MODE
  if (ARENA_MODE_IDS.includes(state?.activeModeV2)) return state.activeModeV2;
  if (profile?.mode === "3v3") return "3V3_ARENA";
  if (profile?.mode === "5v5") return "GROUP_STRATEGY";
  return "1V1_ARENA";
}
function EvidenceBadge({ value }: { value: string }) { return <span className={`arena-chip trust-${value.toLowerCase().replaceAll("_", "-")}`}>{evidenceLabel(value)}</span>; }
function SectionHeader({ eyebrow, title, copy }: { eyebrow?: string; title: string; copy?: string }) { return <div className="arena-section-heading"><div>{eyebrow && <span className="arena-eyebrow">{eyebrow}</span>}<h2>{title}</h2>{copy && <p>{copy}</p>}</div></div>; }
function Unknown({ children }: { children: React.ReactNode }) { return <div className="arena-validation bad"><Info size={16} /><span><strong>NEEDS CURRENT CLIENT DATA</strong> · {children}</span></div>; }

function WorkspaceSwitcher() { return <nav className="arena-workspace-switcher" aria-label="Product workspaces"><button type="button" onClick={() => { location.hash = "#pve/overview"; }}>PvE<small>Boss Lab</small></button><button type="button" className="is-active" aria-current="page">Arena<small>PvP Lab V2</small></button><button type="button" onClick={() => { location.hash = "#training-terrace/overview"; }}>Training Terrace<small>Calibration</small></button><button type="button" onClick={() => { location.hash = "#gvg/overview"; }}>Guild War<small>War Room V2</small></button></nav>; }

function ModePicker({ mode, onChange }: { mode: ArenaModeV2; onChange: (mode: ArenaModeV2) => void }) {
  return <div className="arena-mode-picker" aria-label="Arena mode">{ARENA_MODE_IDS.map((id) => <button key={id} type="button" className={mode === id ? "is-active" : ""} onClick={() => onChange(id)}>{ARENA_MODE_RULES[id].label}</button>)}</div>;
}

function ModeTruth({ mode }: { mode: ArenaModeV2 }) {
  const rule = ARENA_MODE_RULES[mode];
  const stats = canOptimizeNumericStats(mode);
  const attune = attunementDecision(mode);
  return <article className="arena-card" data-testid="arena-mode-truth"><div className="arena-result-head"><div><span className="arena-kicker">MODE CONTRACT</span><h3>{rule.label}</h3></div><EvidenceBadge value={rule.scheduleEvidence} /></div><div className="arena-three-col"><div><strong>Schedule</strong><p>{rule.schedule}</p></div><div><strong>Environment</strong><p>{rule.environment}</p></div><div><strong>Level Adjustment</strong><p>{rule.levelAdjustment === true || rule.levelAdjustment === EVIDENCE_STATE.CONFIRMED_OFFICIAL ? "Confirmed context" : evidenceLabel(String(rule.levelAdjustment))}</p></div></div>{!stats.allowed && <Unknown>{stats.reason}</Unknown>}{!attune.resolved && <Unknown>Attunement applicability for this mode is unresolved; no gear ranking can depend on an assumed profile.</Unknown>}</article>;
}

function Overview({ mode, setMode, profile, state }: { mode: ArenaModeV2; setMode: (m: ArenaModeV2) => void; profile: any; state: ArenaState }) {
  const rule = ARENA_MODE_RULES[mode];
  return <div data-testid="arena-overview"><SectionHeader eyebrow="Arena V2 / Mode first" title="Choose the ruleset before the build" copy="1v1, 3v3, Group Strategy, 5v5, Perception Forest and Training Terrace no longer share one scenario object." /><article className="arena-hero-card"><div className="arena-hero-copy"><span className="arena-kicker">ACTIVE COMPETITIVE CONTEXT</span><h3>{rule.label}</h3><p>{profile.path} · {(profile.weapons || []).join(" + ")}</p><div className="arena-chip-row"><EvidenceBadge value={rule.scheduleEvidence} /><span className="arena-chip">{profile.battlegroup || "Jiangzhu"}</span></div></div><ModePicker mode={mode} onChange={setMode} /></article><ModeTruth mode={mode} />{mode === "3V3_ARENA" && <ThreeVThree />}{mode === "PERCEPTION_FOREST" && <PerceptionForest />}{mode === "TRAINING_TERRACE" && <article className="arena-card"><span className="arena-kicker">CALIBRATION ONLY</span><h3>Training Terrace is not ranked truth</h3><p>Use Preliminary/Training behavior to capture current client stat and Attunement changes. Do not promote a training-only effect to standard Arena without evidence.</p></article>}<div className="arena-three-col"><article className="arena-card"><span className="arena-kicker">NEXT: BUILD</span><h4>Applicability gate</h4><p>Numeric equipment recommendations stay disabled until selected-mode stat applicability is established.</p><button type="button" onClick={() => go("build")}>Open Build <ChevronRight size={15}/></button></article><article className="arena-card"><span className="arena-kicker">NEXT: MATCHUP</span><h4>Mechanic interactions</h4><p>Compare engage, stagger, Tenacity, Super Armor, Qi/Endurance pressure, escapes and conversion windows.</p><button type="button" onClick={() => go("matchups")}>Open Matchup Lab <ChevronRight size={15}/></button></article><article className="arena-card"><span className="arena-kicker">FRESHNESS</span><h4>{COMPETITIVE_PATCH}</h4><p>{EVIDENCE_MATRIX.filter((row) => row.mode.includes("ARENA") || row.mode.includes("3V3") || row.mode === "PERCEPTION_FOREST").length} high-impact Arena evidence records encoded.</p></article></div></div>;
}

function Build({ mode, profile, state, setState }: { mode: ArenaModeV2; profile: any; state: ArenaState; setState: (s: ArenaState) => void }) {
  const guard = canOptimizeNumericStats(mode); const attune = attunementDecision(mode);
  const importPve = () => { const snapshot = readPveInventorySnapshot(); setState({ ...state, profiles: state.profiles.map((p: any) => p.id === state.activeProfileId ? { ...p, gearSnapshot: snapshot } : p) } as ArenaState); };
  return <div data-testid="arena-build"><SectionHeader eyebrow="Arena V2 / Build" title="Build decision with applicability guards" copy="The selected mode controls whether a stat can enter an optimization decision. PvE DPS is never an Arena ranking input." /><ModeTruth mode={mode}/><div className="arena-two-col wide-left"><article className="arena-card"><span className="arena-kicker">READ-ONLY GEAR SNAPSHOT</span>{profile.gearSnapshot ? <><h3>{profile.gearSnapshot.schemeName || "Imported build"}</h3><p>Snapshot only; Arena does not write back into PvE inventory.</p></> : <><Database size={24}/><h3>No snapshot yet</h3><p>Import current gear for inspection; unresolved mode-normalization fields will still be blocked.</p></>}<button type="button" onClick={importPve}><Download size={15}/> Use My Current Gear</button></article><article className="arena-card"><span className="arena-kicker">ATTUNEMENT APPLICABILITY</span><h3>Normal + Arena stacking = OFF</h3><p>Normal: {evidenceLabel(attune.normal)} · Arena: {evidenceLabel(attune.arena)}</p>{!attune.resolved && <Unknown>Do not rank Attunement-dependent gear for {ARENA_MODE_RULES[mode].label}.</Unknown>}</article></div><article className="arena-card" data-testid="arena-best-build"><span className="arena-kicker">BEST BUILD V2</span><h3>{guard.allowed ? "Tradeoff candidates" : "Optimizer locked"}</h3>{guard.allowed ? <p>Show Pareto candidates by burst, survival, Qi economy and support instead of one weighted PvP score.</p> : <><p>No universal winner. Current mode has unresolved normalized/stat fields.</p><Unknown>Unknown fields include {guard.unknownFields.slice(0, 8).join(", ")}{guard.unknownFields.length > 8 ? "…" : ""}.</Unknown></>}<div className="arena-two-col"><div><strong>Candidate A</strong><p>Better burst / conversion.</p></div><div><strong>Candidate B</strong><p>Better survival / Qi economy.</p></div></div><p className="arena-muted"><strong>NO UNIVERSAL WINNER</strong> when tradeoffs are multidimensional.</p></article></div>;
}

function ThreeVThree() {
  const [healer, setHealer] = useState(false); const [sameCount, setSameCount] = useState(2); const [royal, setRoyal] = useState(false);
  const rule = validate3v3Rules({ healer, sameMartialArtCount: sameCount, royalRemedyT6: royal });
  return <article className="arena-card" data-testid="arena-3v3-composition"><div className="arena-result-head"><div><span className="arena-kicker">3V3 BRANCH ENGINE</span><h3>{rule.branch.replaceAll("_", " ")}</h3></div><EvidenceBadge value={EVIDENCE_STATE.CONFIRMED_OFFICIAL}/></div><div className="arena-inline-controls"><label><input type="checkbox" checked={healer} onChange={(e) => setHealer(e.target.checked)}/> Team has healer</label><label>Same Martial Art max count<input aria-label="Same Martial Art count" type="number" min={1} max={3} value={sameCount} onChange={(e) => setSameCount(Number(e.target.value))}/></label>{healer && <label><input type="checkbox" checked={royal} onChange={(e) => setRoyal(e.target.checked)}/> Royal Remedy T6 exception observed</label>}</div>{!healer ? <p>One revive opportunity · 10m range · 15s window · successful revive grants temporary Physical Attack buff (exact magnitude/duration not fabricated).</p> : <p>Panacea Fan Resurrection restriction applies; Royal Remedy T6 is an explicit exception only when confirmed for the current branch.</p>}<div className={`arena-validation ${rule.valid ? "ok" : "bad"}`}><ShieldCheck size={16}/><span>{rule.valid ? "Same Martial Art ≤ 2 per team." : rule.violations.join(" ")}</span></div></article>;
}

function Matchups({ mode, profile, opponent, setOpponent }: { mode: ArenaModeV2; profile: any; opponent: string; setOpponent: (v: string) => void }) {
  const result = useMemo(() => matchupAnalysis({ myPath: profile.path, opponentPath: opponent, mode }), [profile.path, opponent, mode]);
  return <div data-testid="arena-matchups"><SectionHeader eyebrow="Arena V2 / Matchups" title="Mechanic matchup lab" copy="No generic 1–5 score and no fake win probability. The result is a structured interaction checklist." /><article className="arena-matchup-picker"><div><span>MY PATH</span><strong>{profile.path}</strong><small>{ARENA_MODE_RULES[mode].label}</small></div><Swords size={24}/><label>OPPONENT PATH<select aria-label="Opponent Path" value={opponent} onChange={(e) => setOpponent(e.target.value)}>{PATHS.map((path) => <option key={path}>{path}</option>)}</select></label></article><article className="arena-card arena-result" data-testid="arena-matchup-result"><div className="arena-result-head"><div><span className="arena-kicker">{profile.path} vs {opponent}</span><h3>Interaction analysis</h3></div><EvidenceBadge value={result.confidence}/></div><div className="arena-three-col"><ListBlock title="ADVANTAGES" rows={result.advantages}/><ListBlock title="RISKS" rows={result.risks}/><ListBlock title="KEY INTERACTIONS" rows={result.keyInteractions}/></div><div className="arena-two-col"><ListBlock title="PUNISH WINDOWS" rows={result.punishWindows}/><ListBlock title="DEFENSIVE ANSWERS" rows={result.defensiveAnswers}/></div><ListBlock title="UNKNOWN / PLAYER-SKILL-SENSITIVE" rows={result.unknowns}/><p className="arena-muted">This is not an empirical win probability.</p></article>{mode === "3V3_ARENA" && <ThreeVThree/>}{mode === "PERCEPTION_FOREST" && <PerceptionForest/>}</div>;
}
function ListBlock({ title, rows }: { title: string; rows: string[] }) { return <div><strong>{title}</strong>{rows.length ? <ul>{rows.map((row) => <li key={row}>{row}</li>)}</ul> : <p className="arena-muted">No current evidence-backed claim.</p>}</div>; }

function Compare({ mode }: { mode: ArenaModeV2 }) { const guard = canOptimizeNumericStats(mode); return <div data-testid="arena-compare"><SectionHeader eyebrow="Arena V2 / Compare" title="Tradeoff compare" copy="Compare mechanic envelopes; do not import 1106/1129 PvE DPS ordering as Arena truth."/><article className="arena-card"><h3>Build A vs Build B</h3><div className="arena-two-col"><div><strong>A</strong><p>Burst / conversion / pressure focus.</p></div><div><strong>B</strong><p>Survival / Qi economy / peel focus.</p></div></div><p><strong>NO UNIVERSAL WINNER.</strong> Select the mode and matchup objective before deciding.</p>{!guard.allowed && <Unknown>Numeric stat delta comparison is disabled because selected-mode stat applicability is unresolved.</Unknown>}</article></div>; }

function Simulation() {
  let state = createArenaCombatState({ hp: 70, qi: 70, state: "HIT_STAGGER", tags: ["CONTROLLED"] });
  state = applyCombatEvent(state, { t: 2, type: "GUARDING_QI_CORE", hpRestore: 8, qiRestore: 10 });
  state = applyCombatEvent(state, { t: 5, type: "EXECUTED_KNOCKDOWN" });
  state = applyCombatEvent(state, { t: 5.1, type: "QI_DAMAGE", amount: 30 });
  state = applyCombatEvent(state, { t: 6, type: "GET_UP" });
  return <div data-testid="arena-simulation"><SectionHeader eyebrow="Arena V2 / Simulation" title="Combat state & resource engine" copy="Discrete state reasoning only. Unpublished animation/recovery coefficients remain UNKNOWN."/><div className="arena-resource-strip"><div><span>HP</span><strong>{state.hp}</strong></div><div><span>QI</span><strong>{state.qi}</strong></div><div><span>ENDURANCE</span><strong>{state.endurance}</strong></div><div><span>VITALITY</span><strong>{state.vitality}</strong></div><div><span>STATE</span><strong>{state.state}</strong></div></div><article className="arena-card"><h3>Distinct get-up flags</h3><div className="arena-chip-row">{state.tags.map((tag) => <span className="arena-chip" key={tag}>{tag}</span>)}</div><p>Qi Damage ignored during applicable Execute knockdown; Guarding Qi Core is not a generic DR button.</p><p>{NETWORK_RESOLUTION.semantics}</p><p className="arena-muted">Latency context is metadata only; latency damage coefficient = none.</p></article></div>;
}

function PerceptionForest() { const r = PERCEPTION_FOREST.rodentHunt; return <article className="arena-card" data-testid="perception-forest-rules"><span className="arena-kicker">PERCEPTION FOREST · SEPARATE RULESET</span><h3>Mode-specific effects are isolated</h3><p>Poison zone · event bosses · Duel Arena · return Invincibility · special skills/items · Blazing Bow.</p><div className="arena-stat-grid"><div><strong>{r.durationSeconds}s</strong><small>Rodent Hunt</small></div><div><strong>-{r.healingReceivedReductionPct}%</strong><small>received Healing</small></div><div><strong>{r.settlementPctDamageTaken}%</strong><small>damage-taken settlement</small></div></div><p>One active application per target. This effect cannot leak into 1v1/3v3/Group Strategy/Guild War/PvE.</p></article>; }

function Mechanics({ mode }: { mode: ArenaModeV2 }) { return <div data-testid="arena-skills"><SectionHeader eyebrow="Arena V2 / Mechanics" title="Current state/mechanic catalog" copy="Path effects are provenance- and scope-tagged."/>{mode === "PERCEPTION_FOREST" && <PerceptionForest/>}<article className="arena-card"><span className="arena-kicker">BAMBOOCUT-DUST V2</span><h3>Everspring Umbrella + Unfettered Rope Dart</h3><ul><li>Burn and Bury: <strong>unblockable</strong>; golden-flash warning.</li><li>Piercing Dart: Tenacity starts after <strong>{BAMBOOCUT_DUST_ARENA.piercingDart.tenacityStartsAfterSeconds}s</strong>; current-compatible post-cast retention.</li><li>Scarlet Spin: current stagger/tracking; Attunement trigger requires actual Hit Stagger/Control.</li><li>Phantom Rally/Resonance must not interrupt Tenacity.</li><li>Serene Breeze current V2 interaction is Super Armor, not old Tenacity + Control Immunity.</li><li>Dreamwrought +20% is non-player-only and rejected for Arena/Guild War.</li></ul></article></div>; }

function Attunement({ mode }: { mode: ArenaModeV2 }) { const row = attunementDecision(mode); return <div data-testid="arena-attunement"><SectionHeader eyebrow="Arena V2 / Attunement" title="Current Arena Attunement catalog" copy="Normal and Arena profiles are separate; stacking = OFF by default."/><article className="arena-card"><h3>{ARENA_MODE_RULES[mode].label}</h3><p>Normal: <strong>{evidenceLabel(row.normal)}</strong> · Arena: <strong>{evidenceLabel(row.arena)}</strong></p>{!row.resolved && <Unknown>Applicability is unresolved. Do not promote an Attunement-dependent optimizer result.</Unknown>}</article><div className="arena-reference-grid">{ARENA_ATTUNEMENT_CATALOG.map((item) => <article className="arena-card" key={item.id}><div className="arena-result-head"><span className="arena-kicker">{item.slot} · {item.rarity}</span><EvidenceBadge value={item.evidence}/></div><h4>{item.path}</h4><p>{item.effect}</p><small>{item.trigger} · patch {item.patch}</small></article>)}</div></div>; }

function EvidenceView() { return <div data-testid="arena-evidence"><SectionHeader eyebrow="Arena V2 / Evidence" title="Current Global evidence matrix" copy="UNKNOWN is a product state, not a gap hidden behind a slider."/><div className="arena-reference-grid">{EVIDENCE_MATRIX.filter((row) => row.mode !== "GUILD_WAR").map((row) => <article className="arena-card" key={row.id}><div className="arena-result-head"><span className="arena-kicker">{row.mode}</span><EvidenceBadge value={row.evidence}/></div><h4>{row.claim}</h4><p>{row.scope}</p><small>{row.source} · {row.sourceDate}</small></article>)}</div><article className="arena-card"><h3>Minimum client capture</h3><ul>{P0_CLIENT_CAPTURE_CHECKLIST.filter((row) => /3v3|Arena|Group Strategy|Player Target/i.test(row)).map((row) => <li key={row}>{row}</li>)}</ul></article></div>; }

function ReferenceBuilds() { return <div data-testid="arena-reference"><SectionHeader eyebrow="Arena V2 / Paths" title="Evidence-backed competitive path catalog" copy="Only profiles supportable by current evidence are shown; missing paths are not filled with fake ratings."/><div className="arena-reference-grid">{Object.entries(PATH_COMPETITIVE_PROFILES).map(([path, data]: any) => <article className="arena-card" key={path}><div className="arena-result-head"><div><span className="arena-kicker">PATH</span><h3>{path}</h3></div><EvidenceBadge value={data.evidence}/></div><p>{data.weapons.join(" + ")} · {data.range}</p><ListBlock title="Control / stagger" rows={[...data.stagger,...data.control]}/><ListBlock title="Defensive states" rows={[...data.tenacity,...data.superArmor,...data.shielding]}/><ListBlock title="Unknown / counters" rows={data.counters}/></article>)}</div></div>; }

function HistoryView({ profile, mode }: { profile: any; mode: ArenaModeV2 }) {
  const [rows, setRows] = useState<any[]>(() => loadArenaHistory()); const [opponent, setOpponent] = useState(PATHS[1] || PATHS[0]); const [result, setResult] = useState("WIN"); const [notes, setNotes] = useState(""); const [duration, setDuration] = useState("");
  const save = () => { const next = [...rows, { id: `h-${Date.now()}`, date: new Date().toISOString().slice(0,10), patch: COMPETITIVE_PATCH, mode, opponentPath: opponent, result, durationSeconds: duration ? Number(duration) : null, notes, path: profile.path }]; saveArenaHistory(next); setRows(loadArenaHistory()); setNotes(""); };
  return <div data-testid="arena-history"><SectionHeader eyebrow="Arena V2 / History" title="Observed local matches" copy="Descriptive evidence only; no win-rate claim is promoted from tiny samples."/><article className="arena-card arena-form-card"><label>Opponent Path<select aria-label="Opponent Path" value={opponent} onChange={(e) => setOpponent(e.target.value)}>{PATHS.map((p) => <option key={p}>{p}</option>)}</select></label><label>Result<select aria-label="Result" value={result} onChange={(e) => setResult(e.target.value)}><option>WIN</option><option>LOSS</option><option>DRAW</option></select></label><label>Match duration (sec)<input aria-label="Match duration (sec)" value={duration} onChange={(e) => setDuration(e.target.value)} inputMode="numeric"/></label><label>Notes<textarea aria-label="Notes" value={notes} onChange={(e) => setNotes(e.target.value)} maxLength={500}/></label><button type="button" onClick={save}><Save size={15}/> Save local match</button></article><article className="arena-card"><p>n={rows.length}; descriptive record only.</p>{rows.slice().reverse().map((row) => <div key={row.id}><strong>{row.result} · {row.opponentPath}</strong><p>{row.notes}</p></div>)}</article></div>;
}

function Transfer({ profile }: { profile: any }) { const [token, setToken] = useState(""); const generate = () => { const payload = { schemaVersion: 1, type: "ARENA_BUILD", name: profile.name || "Arena V2", path: profile.path, weapons: profile.weapons || [], mode: profile.mode || "1v1", arenaAttunementIds: profile.arenaAttunementIds || [], strengths: ["Mechanic-specific reference"], risks: ["Stat applicability may be UNKNOWN"], maturity: "MODELED", patch: "2.0" }; setToken(`${location.origin}${location.pathname}#arena/shared/${encodeArenaShare(payload)}`); }; return <div data-testid="arena-transfer"><SectionHeader eyebrow="Arena V2 / Share" title="Read-only Arena reference" copy="Sharing does not overwrite the active profile."/><article className="arena-card"><button type="button" onClick={generate}><Upload size={15}/> Generate read-only share</button><label>Arena share token<textarea aria-label="Arena share token" value={token} readOnly/></label></article></div>; }

function SharedLanding({ token, state, setState }: { token: string; state: ArenaState; setState: (s: ArenaState) => void }) { let shared: any = null; let error = ""; try { shared = decodeArenaShare(token); } catch (e: any) { error = e.message; } if (!shared) return <main className="arena-shared"><article className="arena-card"><h2>Invalid Arena share</h2><p>{error}</p></article></main>; const clone = () => { const id = `arena-shared-${Date.now()}`; const profile = { ...state.profiles[0], id, name: shared.name, path: shared.path, weapons: shared.weapons, mode: shared.mode, arenaAttunementIds: shared.arenaAttunementIds || [], normalAttunementProfile: null }; setState({ ...state, profiles: [...state.profiles, profile] } as ArenaState); }; return <main className="arena-shared" data-testid="arena-shared-landing"><article className="arena-card"><span className="arena-kicker">READ-ONLY ARENA BUILD</span><h1>{shared.name}</h1><p>{shared.path} · {(shared.weapons || []).join(" + ")}</p><button type="button" onClick={clone}>CLONE TO MY WORKSPACE</button><p>Clone adds a profile; active profile remains unchanged.</p></article></main>; }

function Inspector({ mode, profile, opponent }: { mode: ArenaModeV2; profile: any; opponent: string }) { const attune = attunementDecision(mode); return <aside className="arena-inspector" aria-label="Arena context inspector"><span className="arena-kicker">MODE CONTEXT</span><h3>{ARENA_MODE_RULES[mode].label}</h3><div className="arena-inspector-row"><span>Path</span><strong>{profile.path}</strong></div><div className="arena-inspector-row"><span>Opponent</span><strong>{opponent}</strong></div><div className="arena-inspector-row"><span>Attunement</span><strong>{evidenceLabel(attune.arena)}</strong></div><div className="arena-inspector-row"><span>Stat optimizer</span><strong>{canOptimizeNumericStats(mode).allowed ? "AVAILABLE" : "LOCKED"}</strong></div><hr/><small>{COMPETITIVE_PATCH}</small></aside>; }

export default function ArenaWorkspace() {
  const [route, setRoute] = useState<Route>(() => routeFromHash()); const [state, setStateRaw] = useState<ArenaState>(() => loadArenaState()); const profile = state.profiles.find((p: any) => p.id === state.activeProfileId) || state.profiles[0];
  const [mode, setModeRaw] = useState<ArenaModeV2>(() => initialMode(state, profile)); const [opponent, setOpponentRaw] = useState(state.opponentPath || PATHS.find((p) => p !== profile.path) || PATHS[0]); const [moreOpen, setMoreOpen] = useState(false);
  const setState = (next: ArenaState) => setStateRaw(saveArenaState(next));
  const setMode = (next: ArenaModeV2) => { setModeRaw(next); setState({ ...state, activeModeV2: next, profiles: state.profiles.map((p: any) => p.id === state.activeProfileId ? { ...p, mode: legacyMode(next) } : p) } as ArenaState); };
  const setOpponent = (next: string) => { setOpponentRaw(next); setState({ ...state, opponentPath: next } as ArenaState); };
  useEffect(() => { const onHash = () => { setRoute(routeFromHash()); setMoreOpen(false); }; addEventListener("hashchange", onHash); return () => removeEventListener("hashchange", onHash); }, []);
  const sharedToken = sharedTokenFromHash(); if (sharedToken) return <SharedLanding token={sharedToken} state={state} setState={setState}/>;
  const content: Record<Route, React.ReactNode> = { overview: <Overview mode={mode} setMode={setMode} profile={profile} state={state}/>, build: <Build mode={mode} profile={profile} state={state} setState={setState}/>, matchups: <Matchups mode={mode} profile={profile} opponent={opponent} setOpponent={setOpponent}/>, compare: <Compare mode={mode}/>, simulation: <Simulation/>, history: <HistoryView profile={profile} mode={mode}/>, attunement: <Attunement mode={mode}/>, skills: <Mechanics mode={mode}/>, evidence: <EvidenceView/>, reference: <ReferenceBuilds/>, transfer: <Transfer profile={profile}/> };
  return <div className="arena-root" data-testid="arena-workspace"><header className="arena-topbar"><button className="arena-brand" type="button" onClick={() => go("overview")}><span>WWM</span><div><strong>WWM Calc</strong><small>Competitive Modes V2</small></div></button><WorkspaceSwitcher/><div className="arena-patch"><span>GLOBAL</span><strong>2.0 V2</strong></div></header><div className="arena-layout"><aside className="arena-rail"><nav aria-label="Arena navigation">{PRIMARY.map(({ id, label, icon: Icon }) => <button type="button" key={id} className={route === id ? "is-active" : ""} onClick={() => go(id)}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="arena-more"><span>MORE</span>{SECONDARY.map((item) => <button type="button" key={item.id} className={route === item.id ? "is-active" : ""} onClick={() => go(item.id)}>{item.label}</button>)}</div></aside><main className="arena-main"><div className="arena-card" style={{ marginBottom: 16 }}><ModePicker mode={mode} onChange={setMode}/></div>{content[route]}</main><Inspector mode={mode} profile={profile} opponent={opponent}/></div><nav className="arena-mobile-nav" aria-label="Arena mobile navigation"><button className={route === "build" ? "is-active" : ""} onClick={() => go("build")}><Shield size={18}/>Build</button><button className={route === "matchups" ? "is-active" : ""} onClick={() => go("matchups")}><Crosshair size={18}/>Matchups</button><button className={route === "compare" ? "is-active" : ""} onClick={() => go("compare")}><ArrowLeftRight size={18}/>Compare</button><button className={route === "history" ? "is-active" : ""} onClick={() => go("history")}><History size={18}/>History</button><button className={moreOpen ? "is-active" : ""} onClick={() => setMoreOpen(!moreOpen)}><MoreHorizontal size={18}/>More</button></nav>{moreOpen && <div className="arena-mobile-more" role="dialog" aria-label="Arena more navigation"><button onClick={() => go("overview")}><Activity size={16}/>Overview</button>{SECONDARY.map((item) => <button key={item.id} onClick={() => go(item.id)}><ChevronRight size={15}/>{item.label}</button>)}</div>}</div>;
}

export { ARENA_HISTORY_KEY, ARENA_STORAGE_KEY };
