export const ARENA_SCHEMA_VERSION: number;
export const ARENA_PATCH: string;
export const ARENA_STORAGE_KEY: string;
export const ARENA_HISTORY_KEY: string;
export const PVE_INVENTORY_KEY: string;
export const EVIDENCE: Record<string, string>;
export const ARENA_MODES: readonly string[];
export const ARENA_STATES: readonly string[];
export const ARCHETYPES: readonly string[];
export const ARENA_ATTUNEMENTS: readonly any[];
export const PATH_PROFILES: Readonly<Record<string, any>>;
export const ARENA_REFERENCE_PRESETS: readonly any[];
export const BAMBOOCUT_DUST_RULES: Readonly<Record<string, any>>;
export const REACTION_PRESETS: Readonly<Record<string, any>>;
export const BATTLEGROUPS: readonly any[];
export const OFFICIAL_RULE_REFERENCES: Readonly<Record<string, string>>;
export function clampEnduranceReduction(value: unknown): number;
export function createCombatState(overrides?: Record<string, any>): any;
export function applyArenaEvent(input: any, event: any): any;
export function matchupCompare(myPath: string, opponentPath: string, mode?: string): any;
export function compareArenaBuilds(a: any, b: any, context?: any): any;
export function rankArenaCandidates(candidates: any[], objective?: string, opponentPath?: string | null): any[];
export function validate3v3Composition(players: any[]): any;
export function simulateTeamArena(input?: any): any;
export function simulateTimeline(input?: any): any;
export function readPveInventorySnapshot(storage?: Storage | any): any;
export function defaultArenaState(): any;
export function loadArenaState(storage?: Storage | any): any;
export function saveArenaState(state: any, storage?: Storage | any): any;
export function validateArenaShare(payload: any): any;
export function encodeArenaShare(payload: any): string;
export function decodeArenaShare(encoded: string): any;
export function sanitizeHistoryEntry(entry: any): any;
export function loadArenaHistory(storage?: Storage | any): any[];
export function saveArenaHistory(rows: any[], storage?: Storage | any): any[];
export function summarizeHistory(rows: any[]): any[];
