import { EVIDENCE } from './evidence-v2.mjs';

export const GVG_PHASE=Object.freeze({PREPARATION:'PREPARATION',OPENING:'OPENING',LANE_RESOURCE_CONTROL:'LANE_RESOURCE_CONTROL',OUTPOST_PHASE:'OUTPOST_PHASE',HALFTIME:'HALFTIME',BULWARK_PRESSURE:'BULWARK_PRESSURE',GOOSE_PRESSURE:'GOOSE_PRESSURE',FORTUNE_TREE_ESCORT:'FORTUNE_TREE_ESCORT',ENDGAME:'ENDGAME'});
export const GVG_PHASES=Object.freeze([
{id:GVG_PHASE.PREPARATION,triggerSeconds:null,evidence:EVIDENCE.UNKNOWN,source:'CLIENT_NEEDED'},
{id:GVG_PHASE.OPENING,triggerSeconds:0,evidence:EVIDENCE.MODELED,source:'MAY27'},
{id:GVG_PHASE.LANE_RESOURCE_CONTROL,triggerSeconds:null,evidence:EVIDENCE.MODELED,source:'MAY27'},
{id:GVG_PHASE.OUTPOST_PHASE,triggerSeconds:180,evidence:EVIDENCE.CONFIRMED_OFFICIAL,source:'MAY27'},
{id:GVG_PHASE.HALFTIME,triggerSeconds:null,evidence:EVIDENCE.UNKNOWN,source:'CLIENT_NEEDED'},
{id:GVG_PHASE.BULWARK_PRESSURE,triggerSeconds:null,evidence:EVIDENCE.UNKNOWN,source:'CLIENT_NEEDED'},
{id:GVG_PHASE.GOOSE_PRESSURE,triggerSeconds:null,evidence:EVIDENCE.UNKNOWN,source:'CLIENT_NEEDED'},
{id:GVG_PHASE.FORTUNE_TREE_ESCORT,triggerSeconds:null,evidence:EVIDENCE.UNKNOWN,source:'CLIENT_NEEDED'},
{id:GVG_PHASE.ENDGAME,triggerSeconds:null,evidence:EVIDENCE.UNKNOWN,source:'CLIENT_NEEDED'}]);

export const GVG_RULES=Object.freeze({rosterCapacity:{value:30,evidence:EVIDENCE.COMMUNITY_CORROBORATED,source:'VCROSS'},outpostSpawnSeconds:{value:180,evidence:EVIDENCE.CONFIRMED_OFFICIAL,source:'MAY27'},outpostOwnershipLockSeconds:{value:60,evidence:EVIDENCE.CONFIRMED_OFFICIAL,source:'MAY27'},outpostRevive:{value:true,evidence:EVIDENCE.CONFIRMED_OFFICIAL,source:'MAY27'},panaceaSameTargetResurrectionLockSeconds:{value:60,evidence:EVIDENCE.CONFIRMED_OFFICIAL,source:'MAY27'},bulwarkProximityDrStacksCap:{value:15,evidence:EVIDENCE.CONFIRMED_OFFICIAL,source:'MAY27'},gooseProximityDrStacksCap:{value:30,evidence:EVIDENCE.CONFIRMED_OFFICIAL,source:'MAY27'},guildWarQiDamageReceivedMultiplier:{value:.5,evidence:EVIDENCE.CONFIRMED_OFFICIAL,source:'MAY27'},bulwarkBreakWeakensEnemyGoose:{value:true,evidence:EVIDENCE.CONFIRMED_OFFICIAL,source:'MAY27'},fortuneTreeInterceptionSlowdownReduced:{value:true,evidence:EVIDENCE.CONFIRMED_OFFICIAL,source:'MAY27'},ignoreInterceptionBreachesWindWall:{value:true,evidence:EVIDENCE.CONFIRMED_OFFICIAL,source:'MAY27'},jungleMonstersPerCamp:{value:1,evidence:EVIDENCE.CONFIRMED_OFFICIAL,source:'MAY27'},neutralBossSpawnJitterSeconds:{value:60,evidence:EVIDENCE.CONFIRMED_OFFICIAL,source:'MAY27'},bulwarkDrPerStack:{value:null,evidence:EVIDENCE.UNKNOWN,source:'CLIENT_NEEDED'},gooseDrPerStack:{value:null,evidence:EVIDENCE.UNKNOWN,source:'CLIENT_NEEDED'},halftimeTriggerSeconds:{value:null,evidence:EVIDENCE.UNKNOWN,source:'CLIENT_NEEDED'},matchDurationSeconds:{value:null,evidence:EVIDENCE.UNKNOWN,source:'CLIENT_NEEDED'},preparationSeconds:{value:null,evidence:EVIDENCE.UNKNOWN,source:'CLIENT_NEEDED'},buildSwappingOutOfCombat:{value:null,evidence:EVIDENCE.UNKNOWN,source:'CLIENT_NEEDED'},victoryRuleOrdering:{value:null,evidence:EVIDENCE.UNKNOWN,source:'CLIENT_NEEDED'}});
export const LEAGUE_SCALING=Object.freeze({DIVINARCHE:{bulwarkBossHpMultiplier:.75,neutralGooseHpMultiplier:.75,neutralGooseAttackMultiplier:.75,source:'MAY27'},JESTING_HERO:{bulwarkBossHpMultiplier:.5,neutralGooseHpMultiplier:.5,neutralGooseAttackMultiplier:.5,source:'MAY27'},STEALTH_JESTER:{bulwarkBossHpMultiplier:.25,neutralGooseHpMultiplier:.25,neutralGooseAttackMultiplier:.25,source:'MAY27'}});
export function halftimeDamageBonusPct(secondsSinceHalftimeEntry){return Math.floor(Math.max(0,Number(secondsSinceHalftimeEntry)||0)/30)*30;}
export const COMMAND_CATALOG=Object.freeze([{id:'IGNORE_INTERCEPTION',name:'Ignore Interception',effect:'Can breach Fortune Tree wind-wall blockade.',cost:null,cooldownSeconds:null,target:'FORTUNE_TREE_ESCORT',duration:null,availability:EVIDENCE.CONFIRMED_OFFICIAL,source:'MAY27'},{id:'QUICK_OPERATION',name:'Command Skill Quick Operation',effect:'Quick Operation does not interrupt combat.',cost:null,cooldownSeconds:null,target:'COMMAND_UI',duration:null,availability:EVIDENCE.CONFIRMED_OFFICIAL,source:'MAY27'}]);
export function commandAvailability(command,{balance,lastCastSeconds,nowSeconds,manualCost=null,manualCooldownSeconds=null}={}){const cost=command?.cost??manualCost,cooldown=command?.cooldownSeconds??manualCooldownSeconds;if(cost==null||cooldown==null)return{available:null,reason:'NEEDS_CURRENT_CLIENT_DATA',evidence:EVIDENCE.UNKNOWN};const enoughCoins=Number(balance)>=Number(cost),ready=lastCastSeconds==null||Number(nowSeconds)>=Number(lastCastSeconds)+Number(cooldown);return{available:enoughCoins&&ready,enoughCoins,ready,evidence:EVIDENCE.MODELED};}
export function leagueScalingFor(league,objective){const row=LEAGUE_SCALING[league];if(!row)return{hpMultiplier:null,attackMultiplier:null,evidence:EVIDENCE.UNKNOWN};if(['BULWARK','ZHANG_BAO','ZHUXIE_GULE'].includes(objective))return{hpMultiplier:row.bulwarkBossHpMultiplier,attackMultiplier:1,evidence:EVIDENCE.CONFIRMED_OFFICIAL};if(['GOOSE','NEUTRAL_MONSTER'].includes(objective))return{hpMultiplier:row.neutralGooseHpMultiplier,attackMultiplier:row.neutralGooseAttackMultiplier,evidence:EVIDENCE.CONFIRMED_OFFICIAL};return{hpMultiplier:null,attackMultiplier:null,evidence:EVIDENCE.UNKNOWN};}
export function simulateGvgObjective({objective,baseHp,league,teamObjectiveDps,nearbyPlayers,manualDrPerStack=null,bulwarkBroken=false}={}){const cap=objective==='GOOSE'?30:objective==='BULWARK'?15:0,stacks=Math.max(0,Math.min(cap,Math.floor(Number(nearbyPlayers)||0))),scale=leagueScalingFor(league,objective),hp=baseHp==null||scale.hpMultiplier==null?null:Number(baseHp)*scale.hpMultiplier,dr=manualDrPerStack==null?null:Math.max(0,Math.min(1,Number(manualDrPerStack))),damageMultiplier=dr==null?null:Math.max(.05,1-stacks*dr),dps=teamObjectiveDps==null||damageMultiplier==null?null:Math.max(0,Number(teamObjectiveDps))*damageMultiplier,killTimeSeconds=hp!=null&&hp>0&&dps!=null&&dps>0?hp/dps:null;return{objective,hp,stacks,drPerStack:dr,damageMultiplier,effectiveDps:dps,killTimeSeconds,bulwarkBroken,gooseAttributeReductionMagnitude:null,evidence:killTimeSeconds==null?EVIDENCE.UNKNOWN:EVIDENCE.MODELED};}
