import { useEffect, useMemo, useState } from "react";
import { Activity, BookOpen, Clock3, Coins, Download, HeartPulse, Map, Save, Share2, Shield, Swords, Upload, Users } from "lucide-react";
import { createShareEnvelope, defaultWorkspace, migrateWorkspace, validateRoster, validateShareEnvelope } from "../gvg/model.js";
import {
  ATTUNEMENT_APPLICABILITY, BAMBOOCUT_DUST_GVG, COMMAND_CATALOG, COMPETITIVE_PATCH, DOCTRINE_TEMPLATES,
  EVIDENCE_MATRIX, EVIDENCE_STATE, GUILD_TECHNIQUES, GVG_EX_CATALOG, GVG_EX_COOLDOWN_RULE,
  GVG_LEAGUE_SCALING, GVG_OFFICIAL_RULES, GVG_PHASES, GVG_ROLES_V2, P0_CLIENT_CAPTURE_CHECKLIST,
  gvgCapabilitySummary, halftimeDamageBonus, objectiveSensitivity,
} from "../competitive/competitive-v2.mjs";
import "./guild-war.css";

type View = "overview" | "roster" | "builds" | "strategy" | "timeline" | "objectives" | "matches" | "commander" | "support" | "share";
type RosterMember = { id: string; name: string; path?: string; roles?: string[]; team?: string; availability?: boolean; notes?: string; capabilities?: string[]; exTechnique?: string; exLevel?: number };
const STORAGE_KEY = "wwm_gvg_workspace_v1";
const BACKUP_KEY = "wwm_gvg_workspace_v1__recovery_backup_v1";
const PHASE_KEY = "wwm_gvg_phase_v2";
const MANUAL_KEY = "wwm_gvg_v2_manual";

function evidenceClass(value: string) { return `evidence evidence-${String(value || "UNKNOWN").toLowerCase().replaceAll("_", "-")}`; }
function EvidenceBadge({ value }: { value: string }) { return <span className={evidenceClass(value)}>{value.replaceAll("_", " ")}</span>; }
function routeFromHash(): View { const match = location.hash.match(/^#gvg\/([a-z-]+)/); const value = match?.[1] || "overview"; return ["overview","roster","builds","strategy","timeline","objectives","matches","commander","support","share"].includes(value) ? value as View : "overview"; }
function go(view: View) { location.hash = `#gvg/${view}`; }
function safeJson(value: string | null, fallback: any) { try { return value ? JSON.parse(value) : fallback; } catch { return fallback; } }
function encodeShare(value: unknown) { const bytes = new TextEncoder().encode(JSON.stringify(value)); let binary = ""; bytes.forEach((byte) => { binary += String.fromCharCode(byte); }); return btoa(binary).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", ""); }
function decodeShare(value: string) { const normalized = value.replaceAll("-", "+").replaceAll("_", "/"); const padded = normalized + "=".repeat((4 - normalized.length % 4) % 4); const bytes = Uint8Array.from(atob(padded), (char) => char.charCodeAt(0)); return JSON.parse(new TextDecoder().decode(bytes)); }

function loadWorkspace() {
  const raw = localStorage.getItem(STORAGE_KEY);
  if (!raw) return { workspace: defaultWorkspace(), recovery: "" };
  try { return { workspace: migrateWorkspace(JSON.parse(raw)), recovery: "" }; }
  catch { if (!localStorage.getItem(BACKUP_KEY)) localStorage.setItem(BACKUP_KEY, raw.slice(0, 250000)); return { workspace: defaultWorkspace(), recovery: "Some saved Guild War data could not be loaded. The original payload is preserved in a bounded recovery backup until you explicitly recover or replace it." }; }
}
function emptyMember(index: number): RosterMember { return { id: `gvg-v2-${Date.now()}-${index}`, name: `Player ${String(index).padStart(2,"0")}`, path: "Bamboocut-Dust", roles: ["FLEX"], team: "Main Ball", availability: true, notes: "", capabilities: ["ANTI_HEAL","AOE_CONTROL","EX_COVERAGE"], exTechnique: "Everspring Umbrella EX", exLevel: 3 }; }
function seededRoster() { return Array.from({ length: 30 }, (_, index) => { const row = emptyMember(index + 1); const role = GVG_ROLES_V2[index % GVG_ROLES_V2.length]; return { ...row, roles: [role], team: index < 12 ? "Main Ball" : index < 21 ? "Flex A" : "Flex B", capabilities: role === "HEALER" ? ["HEALING","RESURRECTION"] : role === "FRONTLINE" ? ["FRONTLINE","PEEL"] : role === "COMMANDER" ? ["COMMANDER"] : row.capabilities }; }); }
function SectionTitle({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) { return <div className="gvg-section-title"><div><span>{eyebrow}</span><h2>{title}</h2></div>{copy && <p>{copy}</p>}</div>; }
function Unknown({ children }: { children: React.ReactNode }) { return <div className="gvg-callout"><Shield size={18}/><div><strong>NEEDS CURRENT CLIENT DATA</strong><p>{children}</p></div></div>; }
function Stat({ label, value, detail }: { label: string; value: string | number; detail?: string }) { return <div className="gvg-stat-card"><small>{label}</small><strong>{value}</strong>{detail && <span>{detail}</span>}</div>; }

function PhaseBar({ phase, setPhase }: { phase: string; setPhase: (value: string) => void }) { return <div className="gvg-official-strip" data-testid="gvg-phase-context"><span><strong>PHASE</strong></span><select aria-label="Guild War current phase" value={phase} onChange={(e) => setPhase(e.target.value)}>{GVG_PHASES.map((row) => <option value={row.id} key={row.id}>{row.id.replaceAll("_", " ")}</option>)}</select><span><strong>Outposts</strong> 3:00</span><span><strong>Bulwark cap</strong> 15</span><span><strong>Goose cap</strong> 30</span><span><strong>Qi damage</strong> ×0.5</span><span><strong>Attunement</strong> UNKNOWN</span></div>; }

function Overview({ phase }: { phase: string }) { const phaseRow = GVG_PHASES.find((row) => row.id === phase)!; return <section className="gvg-section" data-testid="gvg-overview"><SectionTitle eyebrow="WAR ROOM / OVERVIEW" title="Mechanics and phase first" copy="Guild War V2 separates match state, player builds, Guild Techniques and Commander/Fun Coin state. No universal GvG score."/><div className="gvg-grid gvg-grid-2"><article className="gvg-card"><div className="gvg-card-head"><div><span className="gvg-kind">CURRENT PHASE</span><h3>{phase.replaceAll("_", " ")}</h3></div><EvidenceBadge value={phaseRow.evidence}/></div><p>{phaseRow.fixedStart == null ? "Trigger/timing is configurable or UNKNOWN." : `Fixed current official start: ${Math.floor(phaseRow.fixedStart/60)}:${String(phaseRow.fixedStart%60).padStart(2,"0")}`}</p>{phase === "HALFTIME" && <p>At entry: 0% DMG Bonus. Then +30% every 30s. Exact current Global trigger remains UNKNOWN.</p>}</article><article className="gvg-card"><span className="gvg-kind">P0 APPLICABILITY</span><h3>Guild War Attunement = UNKNOWN</h3><p>Normal and Arena Attunement are separate systems, but current reviewed evidence does not establish which is active in Guild War.</p><Unknown>No Guild War gear recommendation may depend on an assumed Attunement profile.</Unknown></article></div><div className="gvg-stat-grid"><Stat label="Roster capacity" value={GVG_OFFICIAL_RULES.rosterCapacity.value} detail="official"/><Stat label="Outposts" value="3:00" detail="top + bottom"/><Stat label="Ownership lock" value="60s" detail="official"/><Stat label="Panacea same-target" value="60s" detail="official"/><Stat label="Neutral boss jitter" value="±1m" detail="base time not fabricated"/><Stat label="Halftime trigger" value="UNKNOWN" detail="configurable"/></div><article className="gvg-card"><span className="gvg-kind">CURRENT DECISION MODEL</span><h3>Capability diagnostics, not one score</h3><p>Healing · anti-heal · frontline · peel · AoE control · Qi pressure · EX coverage · objective burn · mobility · duelist availability · resurrection · commander coverage.</p></article></section>; }

function Roster({ roster, patchRoster }: { roster: RosterMember[]; patchRoster: (rows: RosterMember[]) => void }) { const validation = validateRoster(roster as any); const add = () => roster.length < 30 && patchRoster([...roster, emptyMember(roster.length + 1)]); return <section className="gvg-section" data-testid="gvg-roster"><SectionTitle eyebrow="WAR ROOM / ROSTER" title="30-player roster + phase capabilities" copy="Roles are assignments/capabilities, not weighted combat scores."/><div className="gvg-toolbar"><button type="button" className="gvg-button" onClick={() => patchRoster(seededRoster())}><Users size={16}/> Seed 30-player sample</button><button type="button" className="gvg-button" onClick={add} disabled={roster.length >= 30}>Add member</button><span>{roster.length}/30 · {validation.valid ? "valid" : "over capacity"}</span></div><div className="gvg-roster-list">{roster.map((member, index) => <article className="gvg-card" key={member.id}><div className="gvg-grid gvg-grid-2"><label>Player name<input aria-label="Player name" value={member.name} onChange={(e) => patchRoster(roster.map((row) => row.id === member.id ? { ...row, name: e.target.value } : row))}/></label><label>Primary role<select value={member.roles?.[0] || "FLEX"} onChange={(e) => patchRoster(roster.map((row) => row.id === member.id ? { ...row, roles: [e.target.value] } : row))}>{GVG_ROLES_V2.map((role) => <option key={role}>{role}</option>)}</select></label><label>Path<input value={member.path || ""} onChange={(e) => patchRoster(roster.map((row) => row.id === member.id ? { ...row, path: e.target.value } : row))}/></label><label>Squad<input value={member.team || ""} onChange={(e) => patchRoster(roster.map((row) => row.id === member.id ? { ...row, team: e.target.value } : row))}/></label></div><div className="gvg-role-chips">{Object.entries(gvgCapabilitySummary(member)).filter(([, enabled]) => enabled).map(([cap]) => <span key={cap}><strong>{cap}</strong></span>)}</div><button className="gvg-link" type="button" onClick={() => patchRoster(roster.filter((row) => row.id !== member.id))}>Remove #{index + 1}</button></article>)}</div></section>; }

function Builds() { return <section className="gvg-section" data-testid="gvg-builds"><SectionTitle eyebrow="WAR ROOM / BUILDS" title="Phase capability profiles" copy="Personal damage, Qi pressure, anti-heal and objective utility stay separate. No 0–100 GvG score."/><div className="gvg-grid gvg-grid-2"><article className="gvg-card gvg-feature-card"><div className="gvg-card-head"><div><span className="gvg-kind">BAMBOOCUT-DUST</span><h3>Everspring Umbrella + Unfettered Rope Dart</h3></div><EvidenceBadge value={EVIDENCE_STATE.CONFIRMED_OFFICIAL}/></div><div className="gvg-stat-grid"><Stat label="Everspring EX" value={`${BAMBOOCUT_DUST_GVG.antiHeal.basePct}%`} detail={`Lv3 ${BAMBOOCUT_DUST_GVG.antiHeal.lv3Pct}%`}/><Stat label="Unfettered EX" value={`${BAMBOOCUT_DUST_GVG.unfetteredRadiusMeters.value}m`} detail="hit radius"/><Stat label="Guild War Qi" value="×0.5" detail="damage received rule"/><Stat label="Post-death Immobilize" value="NO" detail="Aug 2 regression"/></div><p><strong>Good at:</strong> anti-heal zone, control/stagger, EX coverage, outpost/escort pressure.</p><p><strong>Not asserted:</strong> meta status, exact personal DPS ranking, exact objective-burn rank.</p></article><article className="gvg-card"><span className="gvg-kind">ATTUNEMENT GATE</span><h3>Do not select “Guild War: Arena” or “Guild War: Normal” automatically</h3><p>Normal: {ATTUNEMENT_APPLICABILITY.GUILD_WAR.normal} · Arena: {ATTUNEMENT_APPLICABILITY.GUILD_WAR.arena}</p><Unknown>Capture the current Guild War gear/Attunement indicator before enabling an Attunement-dependent build recommendation.</Unknown></article></div><article className="gvg-card"><span className="gvg-kind">CURRENT EX CATALOG</span><div className="gvg-compare-table"><div className="gvg-compare-row gvg-compare-header"><span>Technique</span><span>Effect</span><span>Cooldown family</span><span>Evidence</span></div>{GVG_EX_CATALOG.map((item) => <div className="gvg-compare-row" key={item.id}><strong>{item.name}</strong><span>{item.effect}</span><span>{item.cooldownFamily || "UNASSIGNED"}</span><small>{item.evidence}</small></div>)}</div><p className="gvg-footnote">Family rule: old/base 120s → {GVG_EX_COOLDOWN_RULE.base120FamilyCurrentSeconds}s; 90s → {GVG_EX_COOLDOWN_RULE.base90FamilyCurrentSeconds}s. Family assignment remains blank unless base cooldown is verified.</p></article><article className="gvg-card"><span className="gvg-kind">GUILD TECHNIQUES</span>{GUILD_TECHNIQUES.map((tech) => <p key={tech.id}><strong>{tech.name}</strong> · {tech.effect} · {tech.evidence}</p>)}</article></section>; }

function Strategy({ phase, roster }: { phase: string; roster: RosterMember[] }) { const [assignments, setAssignments] = useState<Record<string,string>>(() => safeJson(localStorage.getItem("wwm_gvg_v2_assignments"), {})); const objectives = ["TOP_OUTPOST","BOTTOM_OUTPOST","JUNGLE","BULWARK","GOOSE","FORTUNE_TREE","FALLBACK"]; const assign = (id: string, squad: string) => { const next = { ...assignments, [id]: squad }; setAssignments(next); localStorage.setItem("wwm_gvg_v2_assignments", JSON.stringify(next)); }; return <section className="gvg-section" data-testid="gvg-strategy"><SectionTitle eyebrow="WAR ROOM / STRATEGY" title="Phase-linked objective board" copy="Map/timeline objective IDs are shared; each objective exposes assignment and uncertainty."/><div className="gvg-grid gvg-grid-2"><article className="gvg-card"><span className="gvg-kind">CURRENT PHASE</span><h3>{phase.replaceAll("_", " ")}</h3><p>{roster.length} roster members available in this plan.</p></article><article className="gvg-card"><span className="gvg-kind">DOCTRINE</span><h3>Custom / mechanic diagnostics</h3><p>No fixed healer/tank count. Historical/community templates remain references only.</p></article></div><div className="gvg-grid gvg-grid-2">{objectives.map((id) => <article className="gvg-card" data-objective-id={id} key={id}><h3>{id.replaceAll("_", " ")}</h3><label>Assigned squad<input value={assignments[id] || ""} onChange={(e) => assign(id, e.target.value)} placeholder="Main Ball / Flex A"/></label><p><strong>EX coverage:</strong> manual from roster assignment.</p><p><strong>Next command:</strong> current cost/CD may be UNKNOWN.</p>{id === "BULWARK" || id === "GOOSE" ? <Unknown>Exact DR-per-stack remains unresolved.</Unknown> : null}</article>)}</div></section>; }

function Timeline({ phase }: { phase: string }) { const [halftimeTrigger, setHalftimeTrigger] = useState(() => safeJson(localStorage.getItem(MANUAL_KEY), {}).halftimeTrigger ?? ""); const save = (value: string) => { setHalftimeTrigger(value); const row = safeJson(localStorage.getItem(MANUAL_KEY), {}); localStorage.setItem(MANUAL_KEY, JSON.stringify({ ...row, halftimeTrigger: value })); }; return <section className="gvg-section" data-testid="gvg-timeline"><SectionTitle eyebrow="WAR ROOM / TIMELINE" title="Fixed facts + configurable phase boundaries" copy="Only Outpost 3:00 is hard-coded. Halftime trigger remains a manual Advanced parameter."/><div className="gvg-compare-table"><div className="gvg-compare-row gvg-compare-header"><span>Phase</span><span>Start</span><span>Evidence</span><span>Context</span></div>{GVG_PHASES.map((row) => <div className="gvg-compare-row" key={row.id}><strong>{row.id.replaceAll("_", " ")}</strong><span>{row.fixedStart == null ? "UNKNOWN/config" : `${Math.floor(row.fixedStart/60)}:${String(row.fixedStart%60).padStart(2,"0")}`}</span><span>{row.evidence}</span><small>{row.id === phase ? "CURRENT" : ""}</small></div>)}</div><article className="gvg-card"><label>Advanced · Halftime trigger (seconds)<input aria-label="Halftime trigger override" value={halftimeTrigger} onChange={(e) => save(e.target.value)} placeholder="UNKNOWN" inputMode="numeric"/></label><div className="gvg-stat-grid">{[0,30,60,90].map((seconds) => <Stat key={seconds} label={`+${seconds}s after entry`} value={`${halftimeDamageBonus(seconds)}%`} detail="DMG Bonus"/>)}</div><p>At entry = 0%; +30% every 30 seconds. Trigger time is not inferred from old guides.</p></article></section>; }

function Objectives() { const [objective, setObjective] = useState("BULWARK"); const [baseHp, setBaseHp] = useState(""); const [teamDps, setTeamDps] = useState(""); const [dr, setDr] = useState(""); const [league, setLeague] = useState("DIVINARCHE"); const rows = [5,10,15,20,25,30].map((nearbyPlayers) => objectiveSensitivity({ objective, baseHp: baseHp ? Number(baseHp) : null, teamDps: teamDps ? Number(teamDps) : null, nearbyPlayers, drPerStack: dr ? Number(dr) : null, league })); return <section className="gvg-section" data-testid="gvg-objectives"><SectionTitle eyebrow="WAR ROOM / OBJECTIVES" title="Transparent sensitivity, no fake kill time" copy="Base HP, calibrated team objective DPS and DR-per-stack must be known/manual before a time is shown."/><article className="gvg-card"><div className="gvg-grid gvg-grid-2"><label>Objective<select value={objective} onChange={(e) => setObjective(e.target.value)}><option>BULWARK</option><option>GOOSE</option></select></label><label>League<select value={league} onChange={(e) => setLeague(e.target.value)}>{Object.keys(GVG_LEAGUE_SCALING).map((id) => <option key={id}>{id}</option>)}</select></label><label>Advanced · base HP<input aria-label="Objective base HP" value={baseHp} onChange={(e) => setBaseHp(e.target.value)} placeholder="UNKNOWN"/></label><label>Advanced · calibrated team objective DPS<input aria-label="Team objective DPS" value={teamDps} onChange={(e) => setTeamDps(e.target.value)} placeholder="UNKNOWN"/></label><label>Advanced · DR per stack<input aria-label="DR per stack" value={dr} onChange={(e) => setDr(e.target.value)} placeholder="UNKNOWN"/></label></div>{!dr && <Unknown>Exact {objective} DR-per-stack is not published in the reviewed evidence.</Unknown>}</article><div className="gvg-compare-table"><div className="gvg-compare-row gvg-compare-header"><span>Nearby</span><span>Stacks</span><span>Effective DPS</span><span>Kill time</span></div>{rows.map((row) => <div className="gvg-compare-row" key={row.stacks + ":" + row.objective}><strong>{row.stacks === 15 && objective === "BULWARK" ? "15+" : row.stacks}</strong><span>{row.stacks}</span><span>{row.effectiveDps == null ? "UNKNOWN" : Math.round(row.effectiveDps).toLocaleString()}</span><small>{row.killTimeSeconds == null ? "UNKNOWN" : `${row.killTimeSeconds.toFixed(1)}s modeled`}</small></div>)}</div></section>; }

function Commander() { const [balance, setBalance] = useState(0); const [manualCost, setManualCost] = useState(""); const [manualCd, setManualCd] = useState(""); const command = COMMAND_CATALOG[0]; return <section className="gvg-section" data-testid="gvg-commander"><SectionTitle eyebrow="WAR ROOM / COMMANDER" title="Fun Coin economy + command availability" copy="Current term is Fun Coins. Unpublished current costs/cooldowns stay manual Advanced parameters."/><div className="gvg-grid gvg-grid-2"><article className="gvg-card"><span className="gvg-kind">BALANCE</span><h3>{balance} Fun Coins</h3><div className="gvg-inline-controls"><button onClick={() => setBalance(balance + 100)}>+100 income</button><button onClick={() => setBalance(Math.max(0,balance - Number(manualCost || 0)))} disabled={!manualCost}>Cast manual cost</button></div></article><article className="gvg-card"><div className="gvg-card-head"><h3>{command.name}</h3><EvidenceBadge value={command.evidence}/></div><p>{command.effect}</p><label>Advanced · current cost<input aria-label="Command cost override" value={manualCost} onChange={(e) => setManualCost(e.target.value)} placeholder="UNKNOWN"/></label><label>Advanced · current cooldown<input aria-label="Command cooldown override" value={manualCd} onChange={(e) => setManualCd(e.target.value)} placeholder="UNKNOWN"/></label>{(!manualCost || !manualCd) && <Unknown>Do not copy January cost/CD values.</Unknown>}</article></div></section>; }

function Support() { return <section className="gvg-section" data-testid="gvg-support"><SectionTitle eyebrow="WAR ROOM / SUPPORT" title="Healing / duel / calibration contracts" copy="The official dummy exposes a Guild War environment. Record observed healing/shield/anti-heal/revive data with environment attached."/><article className="gvg-card"><h3>Future observed fields</h3><p>HPS · burst heal · sustained heal · shield · anti-heal exposure · revive · Endurance support.</p><Unknown>Healer coefficients are not invented. Capture the Guild War dummy/client environment first.</Unknown></article><article className="gvg-card"><h3>Guild Technique context</h3>{GUILD_TECHNIQUES.map((item) => <p key={item.id}><strong>{item.name}</strong> · {item.evidence}</p>)}</article></section>; }

function Matches({ workspace, patchWorkspace }: { workspace: any; patchWorkspace: (patch: any) => void }) { const [opponent,setOpponent] = useState(""); const [result,setResult] = useState("WIN"); const [notes,setNotes] = useState(""); const logs = Array.isArray(workspace.matchLogs) ? workspace.matchLogs : []; const save = () => { patchWorkspace({ matchLogs: [...logs, { id: `gvg-log-${Date.now()}`, date: new Date().toISOString().slice(0,10), patch: COMPETITIVE_PATCH, opponent, result, notes }] }); setNotes(""); }; return <section className="gvg-section" data-testid="gvg-matches"><SectionTitle eyebrow="WAR ROOM / MATCH LOG" title="Observed match evidence" copy="Descriptive records can close UNKNOWNs later; they do not create a universal score."/><article className="gvg-card gvg-form-card"><label>Opponent<input value={opponent} onChange={(e) => setOpponent(e.target.value)}/></label><label>Result<select value={result} onChange={(e) => setResult(e.target.value)}><option>WIN</option><option>LOSS</option><option>DRAW</option></select></label><label>Notes<textarea value={notes} onChange={(e) => setNotes(e.target.value)} /></label><button className="gvg-button" onClick={save}><Save size={15}/> Save match</button></article>{logs.slice().reverse().map((row: any) => <article className="gvg-card" key={row.id}><strong>{row.result} · {row.opponent}</strong><p>{row.notes}</p></article>)}</section>; }

function Share({ workspace, setWorkspace }: { workspace: any; setWorkspace: (value: any) => void }) { const [text,setText] = useState(""); const [status,setStatus] = useState(""); const exportJson = () => { const envelope = createShareEnvelope("FULL_GUILD_WAR_PLAN", workspace, { redactPlayerNames: true }); setText(JSON.stringify(envelope,null,2)); setStatus("Versioned read-only plan prepared with player names redacted."); }; const copy = async () => { const envelope = createShareEnvelope("FULL_GUILD_WAR_PLAN", workspace, { redactPlayerNames: true }); const link = `${location.origin}${location.pathname}#gvg-share=${encodeShare(envelope)}`; await navigator.clipboard.writeText(link); setText(JSON.stringify(envelope,null,2)); setStatus("Share link copied."); }; const clone = () => { try { const parsed = JSON.parse(text); const validation = validateShareEnvelope(parsed); if (!validation.valid) throw new Error(validation.error); setWorkspace(migrateWorkspace(parsed.payload)); setStatus("Cloned into local Guild War workspace. PvE/Arena state unchanged."); } catch (error) { setStatus(error instanceof Error ? error.message : "Import failed"); } }; return <section className="gvg-section" data-testid="gvg-share"><SectionTitle eyebrow="WAR ROOM / SHARE" title="Versioned Guild War plan" copy="Read-only links redact player names by default and fail closed on malformed input."/><article className="gvg-card"><div className="gvg-inline-controls"><button className="gvg-button" onClick={exportJson}><Download size={15}/> Prepare JSON</button><button className="gvg-button" onClick={copy}><Share2 size={15}/> Copy share link</button><button className="gvg-button" onClick={clone}><Upload size={15}/> Validate & clone</button></div><label>Guild War JSON<textarea aria-label="Guild War JSON" value={text} onChange={(e) => setText(e.target.value)} rows={10}/></label><p role="status">{status}</p></article></section>; }

export default function GuildWarWorkspace({ onClose: _onClose }: { onClose: () => void }) {
  const loaded = useMemo(() => loadWorkspace(), []); const [workspace,setWorkspaceRaw] = useState<any>(loaded.workspace); const [recovery,setRecovery] = useState(loaded.recovery); const [view,setView] = useState<View>(() => routeFromHash()); const [phase,setPhaseRaw] = useState(() => localStorage.getItem(PHASE_KEY) || "PREPARATION");
  const [sharedError,setSharedError] = useState(""); const roster = (workspace.roster || []) as RosterMember[];
  useEffect(() => { const onHash = () => setView(routeFromHash()); addEventListener("hashchange", onHash); return () => removeEventListener("hashchange", onHash); }, []);
  useEffect(() => { if (!recovery) localStorage.setItem(STORAGE_KEY, JSON.stringify(workspace)); }, [workspace,recovery]);
  useEffect(() => { const marker = "gvg-share="; const index = location.hash.indexOf(marker); if (index < 0) return; try { const envelope = decodeShare(location.hash.slice(index + marker.length)); const validation = validateShareEnvelope(envelope); if (!validation.valid) throw new Error(validation.error); setWorkspaceRaw(migrateWorkspace(envelope.payload)); setSharedError(""); } catch (error) { setSharedError(error instanceof Error ? error.message : "The Guild War share link could not be decoded."); } }, []);
  const patchWorkspace = (patch: any) => setWorkspaceRaw((current: any) => ({ ...current, ...patch })); const patchRoster = (rows: RosterMember[]) => patchWorkspace({ roster: rows });
  const setPhase = (value: string) => { setPhaseRaw(value); localStorage.setItem(PHASE_KEY,value); };
  const recover = () => { const next = defaultWorkspace(); setWorkspaceRaw(next); setRecovery(""); localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); };
  const content: Record<View, React.ReactNode> = { overview: <Overview phase={phase}/>, roster: <Roster roster={roster} patchRoster={patchRoster}/>, builds: <Builds/>, strategy: <Strategy phase={phase} roster={roster}/>, timeline: <Timeline phase={phase}/>, objectives: <Objectives/>, matches: <Matches workspace={workspace} patchWorkspace={patchWorkspace}/>, commander: <Commander/>, support: <Support/>, share: <Share workspace={workspace} setWorkspace={(value) => setWorkspaceRaw(value)}/> };
  return <div className="gvg-overlay" data-testid="guild-war-workspace"><header className="gvg-header"><div><span className="gvg-kicker">GLOBAL GUILD WAR V2</span><h1>War Room</h1><p>Phase · roster · builds · strategy · timeline · objectives · commander · evidence.</p></div><div className="gvg-header-actions"><EvidenceBadge value={EVIDENCE_STATE.CONFIRMED_OFFICIAL}/><button type="button" className="gvg-button" onClick={() => go("share")}><Share2 size={16}/> Share</button></div></header><PhaseBar phase={phase} setPhase={setPhase}/>{recovery && <div className="gvg-card" data-testid="gvg-recovery"><Unknown>{recovery}</Unknown><button className="gvg-button" onClick={recover}>Seed sample / replace corrupt workspace</button><p>Backup key: {BACKUP_KEY}</p></div>}{sharedError && <div className="gvg-card"><Unknown>{sharedError}</Unknown></div>}<nav className="gvg-tabs" aria-label="Guild War workspaces">{([{key:"overview",label:"Overview",icon:Activity},{key:"roster",label:"Roster",icon:Users},{key:"builds",label:"Builds",icon:Swords},{key:"strategy",label:"Strategy",icon:Map},{key:"timeline",label:"Timeline",icon:Clock3},{key:"objectives",label:"Objectives",icon:Shield},{key:"matches",label:"Match Log",icon:BookOpen},{key:"commander",label:"Commander",icon:Coins},{key:"support",label:"Support",icon:HeartPulse}] as any[]).map(({key,label,icon:Icon}) => <button key={key} type="button" className={view === key ? "is-active" : ""} onClick={() => go(key)}><Icon size={17}/><span>{label}</span></button>)}</nav><main className="gvg-main">{content[view]}</main><footer className="gvg-card"><small>{COMPETITIVE_PATCH} · Doctrine references: {DOCTRINE_TEMPLATES.map((row) => row.id).join(" · ")}</small><details><summary>Minimum P0 client evidence</summary><ul>{P0_CLIENT_CAPTURE_CHECKLIST.filter((row) => /Guild War|Commander|Bulwark|Halftime|Player Target/i.test(row)).map((row) => <li key={row}>{row}</li>)}</ul></details></footer></div>;
}
